version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Web management interface
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
      - "rabbitmq_log:/var/log/rabbitmq"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379" # Default Redis port
    volumes:
      - "redis_data:/data"

volumes:
  rabbitmq_data:
  rabbitmq_log:
  redis_data:
